### PR TITLE
PG 9.4.4

### PR DESCRIPTION
**Pull request by nhocki**
Upgrade to Postgres 9.4.4

### CODE REVIEW

**Comment by nhocki** [comment]
@lucasmazza @rafaelfranca would you know why the build would fail because it `Could not resolve the dependencies`?

**Comment by lucasmazza** [comment]
@nhocki might be that we have some outdated test setup that is failing on Travis, but I'm not very familiar with our we are testing these modules. I'll see if I can do something to get a clean build on the master branch and then you can update your fork with the fixes.

**Comment by nhocki** [comment]
@lucasmazza thanks! Let me know and I'll rebase against master.

**Comment by nhocki** [comment]
@lucasmazza I'm sorry to _bump_ this, but any progress? Any way I can help?

**Comment by lucasmazza** [comment]
@nhocki sorry for the delay - no luck looking into this, but the builds works as expected with system ruby 2.0.0.

**Pull request closed without merging**
