### PR TITLE
Upgrade to PostgreSQL 9.6

### PR DESCRIPTION
**Pull request by DanielWright**
I hope this isn't out-of-line, but I'd love to get @mhaylock's 9.6 upgrade into the canonical module. ❤️

### CODE REVIEW

**Comment by mhaylock** [comment]
@DanielWright oh not at all - thanks for submitting this. I'd forgotten all about it!

**Comment by tommeier** [comment]
How do we get this merged? Does anything need to change?

**Comment by orien** [comment]
Looks like there are a few specs that reference 9.5 still.

**Comment by DanielWright** [comment]
Closing this in favour of #45, which has passing specs. 🎉

**Pull request closed without merging**
