### PR TITLE
Upgrade to Postgres 9.6

### PR DESCRIPTION
**Pull request by levlozhkin**
#43 with spec references to 9.5 replaced with ones to 9.6, master merged in and tests passing.

Hats off to @mhaylock for the original commit.

### CODE REVIEW

**Review by orien — APPROVED** [review]
+1

Thank you.

**Comment by DeanSingh** [comment]
@orien When will this PR be merged and a new release out?

**Comment by orien** [comment]
@DeanSingh: I am not a Boxen member so cannot do this. @jacobbednarz can you please help release this new PostgreSQL version?

**Comment by jacobbednarz** [comment]
Released as [9.6.0](https://github.com/boxen/puppet-postgresql/releases/tag/9.6.0) to match the postgresql version.

**Comment by orien** [comment]
Thanks @jacobbednarz!

**Pull request merged**
